parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  ecmaVersion: 2018
  sourceType: module
extends:
- airbnb-typescript/base
- plugin:@typescript-eslint/recommended
rules:
  max-len:
  - error
  - code: 85
    tabWidth: 2
    ignoreComments: true
  arrow-parens:
  - error
  - always
  implicit-arrow-linebreak: 0
  import/prefer-default-export: 'off'
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  import/no-cycle: 0
  "@typescript-eslint/lines-between-class-members": 0
  max-classes-per-file: 0
  import/no-extraneous-dependencies: 0
  "@typescript-eslint/explicit-member-accessibility":
    - error
    - accessibility: no-public
  lines-between-class-members: 0
env:
  node: true
