version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment: 
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - IS_WEBHOOK_ENABLED=false
    volumes:
      - ./src:/app/src