version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment: 
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - METRICS_PATH=${METRICS_PATH}
      - APP_NAME=${APP_NAME}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
    volumes:
      - ./src:/app/src