name: Lint

on: [push, release]

jobs:
  lint:
    steps:
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Lint
      run: npm run eslint

