name: Lint

on: [push, release]

jobs:
  lint:
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Lint
      run: npm run eslint

